[general]
title = "Vega-Lite Template Gallery"
logo = ""
iconLogo = "tabler:chart-histogram"

[general.seo]
name = "Vega-Lite Template Gallery"
description = "A collection of Vega-Lite templates for data visualization."
url = "https://example.com"

[directory.search]
placeholder = "Search among {0} diagrams"
showCount = true
icon = "tabler:chart-bar"

[directory.search.tags]
display = "select"   # options: none,select,show-all
intersection = false

[directory.grid]
list = false

[directory.grid.emptyState]
text = "Seems that this entry is missing from the archives."
type = "button"                                              # options: button, simple, link
icon = "tabler:exclamation-mark"

[directory.grid.card]
image = true
border = "shadow" # options: dashed, shadow, outline

[directory.grid.submit]
show = true
first = false
title = "Submit a diagram template"
description = "Submit a diagram template to add to the template gallery."
hideable = true

[directory.featured]
showOnAllPages = true
showOnSide = true
icon = "tabler:star"
labelForCard = "Featured ✨"

[directory.tagPages]
title = "{0} Apps"

[[directory.tags]]
key = "default-tag"
name = "Default Tag"
color = "blue"

[[directory.tags]]
key = "unused-tag"
name = "unused-tag"
color = "green"

[[directory.tags]]
key = "another unused tag"

[header.banner]
show = true
text = "Follow ______ on twitter."
link = "https://x.com/intent/follow?screen_name="
brandText = "Vega-Lite Template Gallery"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Another Link"
href = "https://example.com"
target = "_blank"

[header.actionButton]
text = "Submit a Vega-Lite diagram template"
href = "/submit"

[footer]
description = "Vega-Lite Template Gallery"

[footer.socials.github]
link = ""
icon = "tabler:brand-github"

[footer.socials.facebook]
link = ""
icon = "tabler:brand-facebook"

[footer.socials.instagram]
link = ""
icon = "tabler:brand-instagram"

[footer.socials.x]
link = "https://x.com"
icon = "tabler:brand-twitter"

[footer.socials.youtube]
link = "https://www.youtube.com"
icon = "tabler:brand-youtube"

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"
